name: test

on:
  push:
    branches:
      - main
      - 'feature/**'
      - '!featC' #Para ignorar alguna branch en particular.
    tags: 
      - latest
    paths:
      - '**.js' #Sólo inicia el workflow cuando se pushea algún archivo JS.
      - '!index.js' #Para ignorar un archivo particular JS.
    # branches-ignore:
    #   - null
  # pull_request:
  #   types: [opened, assigned, closed, reopened]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
