name: Matrix
on: push

jobs:
  node-version: 
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
      #max-parallel: 2 #Para limitar la cantidad de jobs que corren en paralelo
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Node version 
        run: node -v 
      - uses: actions/setup-node@v1 #Para usar acciones propias de Github Actions.
        with:
          node-version: ${{ matrix.node_version }}
      - name: Node version 2 
        run: node -v 